### PR TITLE
Fixed bug and cleaned up code at least a bit

### LINKED ISSUE #145: Done deliveries can be accepted again

### PR DESCRIPTION
**Pull request by lauriLukkarinen**
Resolves #145

### CODE REVIEW

File: components/screens/ManageDeliveries/ManageDelivery.tsx [hunk 1]
```diff
@@ -193,157 +206,190 @@ class ManageDelivery extends React.Component<Props, State> {
...
+    const { selectedContact } = this.state;
+
+    if (!accessToken) {
       return;
     }
 
+    const params = navigation.state.params;
+    const deliveryData: DeliveryListItem = params.deliveryListItem;
+    const isNewDelivery: boolean = params.isNewDelivery;
+    const category: ItemGroupCategory = params.category;
```
Comment (jarinykanen) [inline components/screens/ManageDeliveries/ManageDelivery.tsx:219]:
```suggestion
    const { deliveryListItem, isNewDelivery, category } = navigation.state.params;
    const deliveryData: DeliveryListItem = deliveryListItem;
    const isNewDelivery: boolean = isNewDelivery;
    const category: ItemGroupCategory = category;
```

**Review by jarinykanen — APPROVED** [review]
